name: Publish Docker images

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./adminer-dg/Dockerfile
            tag: dg

          - dockerfile: ./adminer-editor/Dockerfile
            tag: editor

          - dockerfile: ./adminer-full/Dockerfile
            tag: full

          - dockerfile: ./adminer-mongo/Dockerfile
            tag: mongo

          - dockerfile: ./adminer-mysql/Dockerfile
            tag: mysql

          - dockerfile: ./adminer-oracle-11/Dockerfile
            tag: oracle-11

          - dockerfile: ./adminer-oracle-12/Dockerfile
            tag: oracle-12

          - dockerfile: ./adminer-postgres/Dockerfile
            tag: postgres

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: dockette/adminer:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
